python VmTranslator.py ProgramFlow\BasicLoop
python VmTranslator.py ProgramFlow\FibonacciSeries
python VmTranslator.py FunctionCalls\SimpleFunction
python VmTranslator.py FunctionCalls\FibonacciElement
python VmTranslator.py FunctionCalls\NestedCall
python VmTranslator.py FunctionCalls\StaticsTest